name = "cf_ai_knowledge_assistant"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[durable_objects.bindings]
name = "KnowledgeAgent"
class_name = "KnowledgeAgent"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["KnowledgeAgent"]

[ai]
binding = "AI"

[env.production]
name = "cf_ai_knowledge_assistant"

